/*
 * DCFBinaryStream.ino
 * example code illustrating time synced from a DCF77 receiver
 * Thijs Elenbaas, 2012
 * This example code is in the public domain.
 
  This example shows the binary stream generated by the 
  pulse train coming from the DCF decoder and the resulting
  time
  In order for this example to give output from the DCF library,
  make sure that logging is turned on in the DCF library. You can 
  do this by adding the   #define VERBOSE_DEBUG 1   in Utils.cpp. 
 */


#include "DCF77.h"
#include "Time.h"
#include <Servo.h> 

#define DCF_PIN 2	         // Connection pin to DCF 77 device
#define DCF_INTERRUPT 0
#define LOCK_CLOSED 2
#define LOCK_OPENED 179

time_t time;
DCF77 DCF = DCF77(DCF_PIN,DCF_INTERRUPT);
int pinRed = 7;
int pinGreen = 6;
int pinBlue = 5;
int pins[3] = {pinRed, pinGreen, pinBlue};
int servoPin = 9;
boolean timeUpdated = false;
Servo servoLock;

int curPin = 2;

void setup() {
  pinMode(pinRed, OUTPUT);
  pinMode(pinGreen, OUTPUT);
  pinMode(pinBlue, OUTPUT);
  servoLock.attach(servoPin);
  servoLock.write(LOCK_CLOSED);
  Serial.begin(9600);
  DCF.Start();
}

void loop() {
  delay(1000);
  time_t DCFtime = DCF.getTime();
  if (DCFtime!=0) {
    setTime(DCFtime);
    timeUpdated = true;
  }
  checkTime();
}

void checkTime(){
  //Serial.println(minute());
  if (timeUpdated) {
    if (minute() > 10) {
      digitalWrite(pinRed, LOW);
      digitalWrite(pinGreen, HIGH);
      servoLock.write(LOCK_OPENED);
    } else {
      digitalWrite(pinRed, HIGH);
      digitalWrite(pinGreen, LOW);
      servoLock.write(LOCK_CLOSED);
    }
  }
}
